SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES = $(PWD)/../src/coordinate_mapper.v
COCOTB_TOPLEVEL = coordinate_mapper
COCOTB_TEST_MODULES = test_coordinate_mapper

include $(shell cocotb-config --makefiles)/Makefile.sim