SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES = $(PWD)/../src/output_generator.v
COCOTB_TOPLEVEL = output_generator
COCOTB_TEST_MODULES = test_output_generator

include $(shell cocotb-config --makefiles)/Makefile.sim