SIM            ?= icarus
TOPLEVEL_LANG  ?= verilog

MOD ?= control_unit

VERILOG_SOURCES  = $(PWD)/../src/$(MOD).v
VERILOG_SOURCES += $(PWD)/test.v

COCOTB_TOPLEVEL      = $(MOD)
COCOTB_TEST_MODULES  = test_$(MOD)

COMPILE_ARGS += -DDUMP_TOP=$(MOD)
COMPILE_ARGS += -DDUMP_FILE=\"test.fst\"
COMPILE_ARGS += -s test

include $(shell cocotb-config --makefiles)/Makefile.sim